-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('HOUSE_SELLING', 'SMALL_HOUSE_RENTING', 'HOUSE_RENTAL_LEASING', 'LAND_SELLING', 'WORKPLACE_LEASING', 'APARTMENT_LEASING');

-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "serviceType" "ServiceType" NOT NULL DEFAULT 'LAND_SELLING';

-- AlterTable
ALTER TABLE "Short" ADD COLUMN     "serviceType" "ServiceType" NOT NULL DEFAULT 'LAND_SELLING';
